name: Deploy previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - uses: pnpm/action-setup@v2

      - name: Use Node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Lint 💅
        run: pnpm lint

      # - name: Test 🧪
      #   run: yarn test --passWithNoTests

      - name: Build 🔨
        run: pnpm run build
        env:
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}

      # - name: Deploy preview 🚀
      #   uses: rossjrw/pr-preview-action@v1
      #   with:
      #     source-dir: ./build/
